fn build_api_router(state: AppState, cors: CorsLayer) -> Router {
    Router::new()
        .route("/", get(root_handler))
        .route("/api/health", get(health_check))
        .route("/api/version", get(get_version))
        .route("/api/status", get(get_system_status))
        .route("/api/logs", get(get_recent_logs))
        .route("/api/dcp/workflow/status", get(get_dcp_workflow_status_handler))
        .route("/api/dcp/workflow/run", post(run_dcp_workflow_handler))
        .route("/api/system/health", get(get_system_health))
        .route("/api/system/preflight", get(get_system_preflight))
        .route("/api/system/mode", get(get_runtime_mode).post(set_runtime_mode))
        .route("/api/system/emergency-stop", post(set_emergency_stop))
        .route("/events", post(ingest_events))
        .route("/api/chat", post(handle_chat))
        .route("/api/jarvis", post(handle_jarvis_command))
        .route("/api/jarvis/channels/web/message", post(handle_jarvis_web_message))
        .route("/api/jarvis/skills", get(list_jarvis_skills))
        .route("/api/jarvis/skills/:skill_name/execute", post(execute_jarvis_skill))
        .route("/api/jarvis/sessions", get(list_jarvis_sessions))
        .route("/api/jarvis/autonomous/start", post(start_jarvis_autonomous))
        .route("/api/recommendations", get(list_recommendations))
        .route("/api/recommendations/:id/approve", post(approve_recommendation))
        .route("/api/recommendations/:id/reject", post(reject_recommendation))
        .route("/api/recommendations/:id/later", post(later_recommendation))
        .route("/api/recommendations/:id/restore", post(restore_recommendation))
        .route("/api/exec-approvals", get(list_exec_approvals))
        .route("/api/exec-approvals/:id/approve", post(approve_exec_approval))
        .route("/api/exec-approvals/:id/reject", post(reject_exec_approval))
        .route("/api/exec-allowlist", get(list_exec_allowlist).post(add_exec_allowlist))
        .route("/api/exec-allowlist/:id", axum::routing::delete(remove_exec_allowlist))
        .route("/api/exec-results", get(list_exec_results))
        .route("/api/project/scan", get(scan_project_handler))
        .route("/api/verify/runtime", post(run_runtime_verification_handler))
        .route("/api/verify/visual", post(run_visual_verification_handler))
        .route("/api/verify/semantic", post(run_semantic_verification_handler))
        .route("/api/verify/performance", post(run_performance_verification_handler))
        .route("/api/verify/consistency", post(run_consistency_verification_handler))
        .route("/api/verify/runs", get(list_verification_runs))
        .route("/api/judgment", post(run_judgment_handler))
        .route("/api/release/baseline", post(set_release_baseline_handler))
        .route("/api/release/gate", post(run_release_gate_handler))
        .route("/api/exec-results/guard", post(run_exec_results_guard_handler))
        .route("/api/quality/score", post(score_quality_handler))
        .route("/api/quality/latest", get(latest_quality_handler))
        .route("/api/patterns/analyze", post(analyze_patterns))
        .route("/api/quality", get(get_quality_metrics))
        .route("/api/recommendations/metrics", get(get_recommendation_metrics))
        .route("/api/routines", get(list_routines).post(create_routine_handler))
        .route("/api/routines/:id", axum::routing::patch(toggle_routine_handler))
        .route("/api/routine-runs", get(list_routine_runs))
        .route("/api/agent/intent", post(agent_intent_handler))
        .route("/api/agent/plan", post(agent_plan_handler))
        .route("/api/agent/execute", post(agent_execute_handler))
        .route("/api/agent/verify", post(agent_verify_handler))
        .route("/api/agent/approve", post(agent_approve_handler))
        .route("/api/agent/nl-runs", get(list_nl_runs_handler))
        .route("/api/agent/nl-metrics", get(nl_run_metrics_handler))
        .route(
            "/api/agent/approval-policies",
            get(list_nl_approval_policies).post(set_nl_approval_policy),
        )
        .route(
            "/api/agent/approval-policies/:key",
            axum::routing::delete(remove_nl_approval_policy),
        )
        .route("/api/agent/goal", post(execute_goal_handler))
        .route("/api/agent/goal/current", get(get_current_goal))
        .route("/api/agent/feedback", post(handle_feedback))
        .route("/api/context/selection", get(get_selection_context))
        .route("/api/sessions", get(list_sessions_handler))
        .route("/api/sessions/:id", get(get_session_handler).delete(delete_session_handler))
        .route("/api/sessions/:id/resume", post(resume_session_handler))
        .layer(axum::middleware::from_fn(auth_middleware))
        .layer(cors)
        .with_state(state)
}
