param(
  [Parameter(ValueFromRemainingArguments = $true)]
  [string[]]$Args
)

$ErrorActionPreference = "Stop"
Set-StrictMode -Version Latest

$scriptDir = $PSScriptRoot
$projectRoot = (Resolve-Path (Join-Path $scriptDir "..")).Path
Set-Location $projectRoot

function Get-EnvValue {
  param(
    [Parameter(Mandatory = $true)][string]$Name,
    [Parameter(Mandatory = $true)][string]$Default
  )
  $value = [Environment]::GetEnvironmentVariable($Name)
  if ([string]::IsNullOrWhiteSpace($value)) {
    return $Default
  }
  return $value
}

function Get-EnvInt {
  param(
    [Parameter(Mandatory = $true)][string]$Name,
    [Parameter(Mandatory = $true)][int]$Default
  )
  $raw = Get-EnvValue -Name $Name -Default "$Default"
  $parsed = 0
  if ([int]::TryParse($raw, [ref]$parsed)) {
    return $parsed
  }
  return $Default
}

$maxChangedFiles = [Math]::Max(1, (Get-EnvInt -Name "STEER_RELEASE_MAX_CHANGED_FILES" -Default 40))
$allowlistFile = Get-EnvValue -Name "STEER_RELEASE_ALLOWLIST_FILE" -Default ".release-allowlist"
$requireAllowlist = (Get-EnvValue -Name "STEER_RELEASE_REQUIRE_ALLOWLIST" -Default "1")
$reportDir = Get-EnvValue -Name "STEER_RELEASE_REPORT_DIR" -Default "scenario_results"
$diffMode = (Get-EnvValue -Name "STEER_RELEASE_DIFF_MODE" -Default "worktree").Trim().ToLowerInvariant()
$timestamp = Get-Date -Format "yyyyMMdd_HHmmss"
$reportPath = Get-EnvValue -Name "STEER_RELEASE_WORKTREE_REPORT" -Default (Join-Path $reportDir "release_worktree_report_$timestamp.txt")

$bootstrapAllowlist = $false
$useStaged = $false
foreach ($arg in $Args) {
  switch ($arg) {
    "--bootstrap-allowlist" { $bootstrapAllowlist = $true }
    "--staged" { $useStaged = $true }
    "--worktree" { $useStaged = $false }
  }
}

if ($useStaged) {
  $diffMode = "staged"
}
if ($diffMode -notin @("worktree", "staged")) {
  $diffMode = "worktree"
}
if ($requireAllowlist -notin @("0", "1")) {
  $requireAllowlist = "1"
}

New-Item -ItemType Directory -Force -Path $reportDir | Out-Null

if ($diffMode -eq "staged") {
  $gitOutput = (& git diff --cached --name-only 2>$null) -join "`n"
} else {
  $gitOutput = (& git status --porcelain 2>$null) -join "`n"
}

$branchName = (& git rev-parse --abbrev-ref HEAD 2>$null)
if ($LASTEXITCODE -ne 0 -or [string]::IsNullOrWhiteSpace($branchName)) {
  $branchName = "unknown"
}

@(
  "Release Worktree Check"
  "branch=$branchName"
  "max_changed_files=$maxChangedFiles"
  "allowlist_file=$allowlistFile"
  "require_allowlist=$requireAllowlist"
  "diff_mode=$diffMode"
  "timestamp=$((Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ'))"
  ""
) | Set-Content -Path $reportPath -Encoding UTF8

if ([string]::IsNullOrWhiteSpace($gitOutput)) {
  Add-Content -Path $reportPath -Value "status=clean"
  Write-Host "release worktree check passed: clean"
  Write-Host "report: $reportPath"
  exit 0
}

$changedPaths = New-Object System.Collections.Generic.List[string]
$outOfScope = New-Object System.Collections.Generic.List[string]

$allowlistEnabled = Test-Path $allowlistFile
$allowlistEntries = New-Object System.Collections.Generic.HashSet[string]([System.StringComparer]::OrdinalIgnoreCase)

if ($allowlistEnabled) {
  foreach ($line in Get-Content -Path $allowlistFile) {
    $trimmed = $line.Trim()
    if ([string]::IsNullOrWhiteSpace($trimmed) -or $trimmed.StartsWith("#")) {
      continue
    }
    [void]$allowlistEntries.Add($trimmed)
  }
}

foreach ($line in ($gitOutput -split "`r?`n")) {
  if ([string]::IsNullOrWhiteSpace($line)) {
    continue
  }

  $path = ""
  if ($diffMode -eq "staged") {
    $path = $line.Trim()
  } else {
    if ($line.Length -lt 4) {
      continue
    }
    $path = $line.Substring(3).Trim()
    if ($path.Contains(" -> ")) {
      $parts = $path.Split(" -> ")
      $path = $parts[$parts.Length - 1]
    }
  }

  if ([string]::IsNullOrWhiteSpace($path)) {
    continue
  }

  [void]$changedPaths.Add($path)
  if ($allowlistEnabled -and -not $allowlistEntries.Contains($path)) {
    [void]$outOfScope.Add($path)
  }
}

$changedCount = $changedPaths.Count
Add-Content -Path $reportPath -Value "status=dirty"
Add-Content -Path $reportPath -Value "changed_count=$changedCount"
Add-Content -Path $reportPath -Value ""
Add-Content -Path $reportPath -Value "[changed_files]"
foreach ($path in $changedPaths) {
  Add-Content -Path $reportPath -Value $path
}
Add-Content -Path $reportPath -Value ""

if ($bootstrapAllowlist) {
  @(
    "# generated by scripts/check_release_worktree.ps1 --bootstrap-allowlist"
    "# $((Get-Date).ToUniversalTime().ToString('yyyy-MM-ddTHH:mm:ssZ'))"
  ) | Set-Content -Path $allowlistFile -Encoding UTF8
  foreach ($path in $changedPaths) {
    Add-Content -Path $allowlistFile -Value $path
  }
  Write-Host "allowlist generated: $allowlistFile ($changedCount files)"
  Write-Host "report: $reportPath"
  exit 0
}

if (-not $allowlistEnabled -and $requireAllowlist -eq "1") {
  Add-Content -Path $reportPath -Value "[violation]"
  Add-Content -Path $reportPath -Value "type=allowlist_missing"
  Add-Content -Path $reportPath -Value "message=dirty worktree requires allowlist file"
  Add-Content -Path $reportPath -Value ""
  Write-Host "release check failed: allowlist file is required ($allowlistFile)"
  Write-Host "report: $reportPath"
  exit 1
}

if ($allowlistEnabled) {
  Add-Content -Path $reportPath -Value "[allowlist]"
  Add-Content -Path $reportPath -Value "enabled=1"
  Add-Content -Path $reportPath -Value "entries=$($allowlistEntries.Count)"
  Add-Content -Path $reportPath -Value ""
}

if ($changedCount -gt $maxChangedFiles) {
  Add-Content -Path $reportPath -Value "[violation]"
  Add-Content -Path $reportPath -Value "type=max_changed_files"
  Add-Content -Path $reportPath -Value "message=changed_count($changedCount) > max_changed_files($maxChangedFiles)"
  Add-Content -Path $reportPath -Value ""
  Write-Host "release check failed: too many changed files ($changedCount > $maxChangedFiles)"
  Write-Host "report: $reportPath"
  exit 1
}

if ($outOfScope.Count -gt 0) {
  Add-Content -Path $reportPath -Value "[violation]"
  Add-Content -Path $reportPath -Value "type=allowlist"
  Add-Content -Path $reportPath -Value "message=files outside allowlist"
  foreach ($path in $outOfScope) {
    Add-Content -Path $reportPath -Value $path
  }
  Add-Content -Path $reportPath -Value ""
  Write-Host "release check failed: files outside allowlist ($($outOfScope.Count))"
  Write-Host "report: $reportPath"
  exit 1
}

Write-Host "release worktree check passed (changed=$changedCount)"
Write-Host "report: $reportPath"
exit 0
