import { useLauncherDispatchFlow } from "@/features/launcher/hooks/useLauncherDispatchFlow";
import { useLauncherIo } from "@/features/launcher/hooks/useLauncherIo";
import { useLauncherPreflight } from "@/features/launcher/hooks/useLauncherPreflight";
import { useLauncherRecoveryFlow } from "@/features/launcher/hooks/useLauncherRecoveryFlow";
import { useLauncherShell } from "@/features/launcher/hooks/useLauncherShell";
import { useLauncherUiHandlers } from "@/features/launcher/hooks/useLauncherUiHandlers";
import { useRecommendationApprovalFlow } from "@/features/launcher/hooks/useRecommendationApprovalFlow";
import type { LauncherRuntimeView } from "@/features/launcher/hooks/useLauncherRuntimeView";

export function useLauncherActions(runtime: LauncherRuntimeView) {
    const { runPreflightCheck, handlePreflightFix } = useLauncherPreflight({
        currentRunId: runtime.runSnapshot?.runId ?? null,
        preflightOk: runtime.preflightOk,
        loadRunDiagnostics: runtime.loadRunDiagnostics,
        loadDodHistory: runtime.loadDodHistory,
        setPreflightChecks: runtime.setPreflightChecks,
        setPreflightOk: runtime.setPreflightOk,
        setPreflightLoading: runtime.setPreflightLoading,
        setPreflightError: runtime.setPreflightError,
        setPreflightCheckedAt: runtime.setPreflightCheckedAt,
        setPreflightActiveApp: runtime.setPreflightActiveApp,
        setShowPreflightDetail: runtime.setShowPreflightDetail,
        setPreflightFixBusy: runtime.setPreflightFixBusy,
        setPreflightFixMessage: runtime.setPreflightFixMessage,
        setResults: runtime.setResults,
        setShowDetailPanel: runtime.setShowDetailPanel,
    });

    const {
        triggerSuccess,
        triggerError,
        handlePin,
        recordRecoveryAction,
        openArtifactPath,
        openExternalTarget,
        copyTextValue,
        copyArtifactPayload,
        togglePinArtifactKey,
    } = useLauncherIo({
        runId: runtime.runSnapshot?.runId ?? null,
        fallbackRunId: runtime.dodHistory[0]?.runId ?? null,
        setSuccessPulse: runtime.setSuccessPulse,
        setShake: runtime.setShake,
        setArtifactActionMessage: runtime.setArtifactActionMessage,
        setArtifactOpenBusy: runtime.setArtifactOpenBusy,
        setPinnedArtifactKeys: runtime.setPinnedArtifactKeys,
        loadRunDiagnostics: runtime.loadRunDiagnostics,
        loadDodHistory: runtime.loadDodHistory,
    });

    const {
        approvingIds,
        approveErrors,
        n8nOpenBusyKey,
        handleApprove,
        openRecommendationTarget,
    } = useRecommendationApprovalFlow({
        recs: runtime.recs,
        refetch: runtime.refetch,
        provisioningUiByRecId: runtime.provisioningUiByRecId,
        setProvisioningUiState: runtime.setProvisioningUiState,
        clearProvisioningUiState: runtime.clearProvisioningUiState,
        addWatchRecommendation: runtime.addWatchRecommendation,
        removeWatchRecommendation: runtime.removeWatchRecommendation,
        setWatchRecommendationCache: runtime.setWatchRecommendationCache,
        openExternalTarget,
        triggerSuccess,
        triggerError,
        setResults: runtime.setResults,
        setShowDetailPanel: runtime.setShowDetailPanel,
    });

    const {
        pollRunStatusUntilTerminal,
        handleResume,
        handleGuidedRecovery,
        runRecoveryAction,
        handleOneClickRecovery,
        handleApprovalDecision,
    } = useLauncherRecoveryFlow({
        safeExecutionMode: runtime.safeExecutionMode,
        activeExecutionProfile: runtime.activeExecutionProfile,
        recoveryActionBusyKey: runtime.recoveryActionBusyKey,
        lastPlanId: runtime.lastPlanId,
        lastStatus: runtime.lastStatus,
        pendingApproval: runtime.pendingApproval,
        runSnapshot: runtime.runSnapshot,
        manualChecklist: runtime.manualChecklist,
        firstFailedArtifactPath: runtime.firstFailedArtifactPath,
        recoveryActions: runtime.recoveryActions,
        loadRunDiagnostics: runtime.loadRunDiagnostics,
        loadDodHistory: runtime.loadDodHistory,
        runPreflightCheck,
        handlePreflightFix,
        openArtifactPath,
        recordRecoveryAction,
        updateExecutionState: runtime.updateExecutionState,
        triggerSuccess,
        triggerError,
        setApprovalBusy: runtime.setApprovalBusy,
        setRecoveryActionBusyKey: runtime.setRecoveryActionBusyKey,
        setResults: runtime.setResults,
        setShowDetailPanel: runtime.setShowDetailPanel,
        setRunPhase: runtime.setRunPhase,
        setLoading: runtime.setLoading,
        setLastStatus: runtime.setLastStatus,
        setPendingApproval: runtime.setPendingApproval,
        setManualChecklist: runtime.setManualChecklist,
    });

    const { dispatchPrompt } = useLauncherDispatchFlow({
        composerMode: runtime.composerMode,
        safeExecutionMode: runtime.safeExecutionMode,
        executionProfile: runtime.executionProfile,
        autoApplyRecommendedProfile: runtime.autoApplyRecommendedProfile,
        profileRecommendation: runtime.profileRecommendation,
        loading: runtime.loading,
        isExecutionLocked: runtime.isExecutionLocked,
        pendingDispatch: runtime.pendingDispatch,
        goalRunAvailable: runtime.goalRunAvailable,
        setGoalRunAvailable: runtime.setGoalRunAvailable,
        lastDispatchRef: runtime.lastDispatchRef,
        pollRunStatusUntilTerminal,
        runPreflightCheck,
        updateExecutionState: runtime.updateExecutionState,
        loadRunDiagnostics: runtime.loadRunDiagnostics,
        loadDodHistory: runtime.loadDodHistory,
        triggerSuccess,
        triggerError,
        setInput: runtime.setInput,
        setExecutionProfile: runtime.setExecutionProfile,
        setActiveExecutionProfile: runtime.setActiveExecutionProfile,
        setLastPlanId: runtime.setLastPlanId,
        setLastStatus: runtime.setLastStatus,
        setRunPhase: runtime.setRunPhase,
        setDispatchBlockedReason: runtime.setDispatchBlockedReason,
        setDispatchBlockedUntilMs: runtime.setDispatchBlockedUntilMs,
        setPendingDispatch: runtime.setPendingDispatch,
        setShowDetailPanel: runtime.setShowDetailPanel,
        setLoading: runtime.setLoading,
        setPendingApproval: runtime.setPendingApproval,
        setRecoveryActionBusyKey: runtime.setRecoveryActionBusyKey,
        setResults: runtime.setResults,
        setRunSnapshot: runtime.setRunSnapshot,
        setStageRuns: runtime.setStageRuns,
        setStageAssertions: runtime.setStageAssertions,
        setArtifactActionMessage: runtime.setArtifactActionMessage,
    });

    const {
        cancelPendingDispatch,
        handleSend,
        handleSuggestionClick,
        handleQuickProgramAction,
        handleTelegramListenerCommand,
        handleKeyDown,
        handleInputPaste,
    } = useLauncherUiHandlers({
        input: runtime.input,
        loading: runtime.loading,
        isExecutionLocked: runtime.isExecutionLocked,
        isComposing: runtime.isComposing,
        selectedIndex: runtime.selectedIndex,
        pendingDispatch: runtime.pendingDispatch,
        navigableItems: runtime.navigableItems,
        inputRef: runtime.inputRef,
        composingSinceRef: runtime.composingSinceRef,
        sendThrottleRef: runtime.sendThrottleRef,
        dispatchPrompt,
        handleApprove,
        setInput: runtime.setInput,
        setIsComposing: runtime.setIsComposing,
        setSelectedIndex: runtime.setSelectedIndex,
        setPendingDispatch: runtime.setPendingDispatch,
        setDispatchBlockedReason: runtime.setDispatchBlockedReason,
        setDispatchBlockedUntilMs: runtime.setDispatchBlockedUntilMs,
        setResults: runtime.setResults,
        setShowDetailPanel: runtime.setShowDetailPanel,
        setLoading: runtime.setLoading,
        setRunPhase: runtime.setRunPhase,
        setPendingApproval: runtime.setPendingApproval,
        setRecoveryActionBusyKey: runtime.setRecoveryActionBusyKey,
        triggerSuccess,
        triggerError,
    });

    runtime.dispatchPromptRef.current = dispatchPrompt;

    const {
        handleBackgroundClick,
        handleComposerModeSelect,
        handleCycleComposerMode,
        handleApplyWebSearchTemplate,
        handleApplySummaryTemplate,
    } = useLauncherShell({
        inputRef: runtime.inputRef,
        scrollRef: runtime.scrollRef,
        prevComposerModeRef: runtime.prevComposerModeRef,
        dispatchPromptRef: runtime.dispatchPromptRef,
        selectedIndex: runtime.selectedIndex,
        navigableItemsLength: runtime.navigableItems.length,
        resultsLength: runtime.results.length,
        suggestionCount: runtime.suggestionRecs.length,
        composerMode: runtime.composerMode,
        autoApplyRecommendedProfile: runtime.autoApplyRecommendedProfile,
        safeExecutionMode: runtime.safeExecutionMode,
        compactLayoutMode: runtime.compactLayoutMode,
        showAdvancedControls: runtime.showAdvancedControls,
        pinnedArtifactKeys: runtime.pinnedArtifactKeys,
        executionProfile: runtime.executionProfile,
        dispatchBlockedUntilMs: runtime.dispatchBlockedUntilMs,
        dispatchNowMs: runtime.dispatchNowMs,
        pendingDispatch: runtime.pendingDispatch,
        pendingApprovalVisible: !!runtime.pendingApproval,
        lastStatus: runtime.lastStatus,
        lastPlanId: runtime.lastPlanId,
        runPhase: runtime.runPhase,
        failedAssertionsCount: runtime.failedAssertions.length,
        preflightOk: runtime.preflightOk,
        isExecutionLocked: runtime.isExecutionLocked,
        showDetailPanel: runtime.showDetailPanel,
        hasDetailContent: runtime.hasDetailContent,
        shouldRenderDetailPanel: runtime.shouldRenderDetailPanel,
        showPreflightPanel: runtime.showPreflightPanel,
        showPreflightDetail: runtime.showPreflightDetail,
        preflightError: runtime.preflightError,
        executionLockHint: runtime.executionLockHint,
        setResults: runtime.setResults,
        setShowDetailPanel: runtime.setShowDetailPanel,
        setAutoApplyRecommendedProfile: runtime.setAutoApplyRecommendedProfile,
        setExecutionProfile: runtime.setExecutionProfile,
        setDispatchNowMs: runtime.setDispatchNowMs,
        setDispatchBlockedUntilMs: runtime.setDispatchBlockedUntilMs,
        setDispatchBlockedReason: runtime.setDispatchBlockedReason,
        setPendingDispatch: runtime.setPendingDispatch,
        setShowDiagnostics: runtime.setShowDiagnostics,
        setManualChecklist: runtime.setManualChecklist,
        setSelectedIndex: runtime.setSelectedIndex,
        setIsComposing: runtime.setIsComposing,
        setComposerMode: runtime.setComposerMode,
        setInput: runtime.setInput,
    });

    return {
        runPreflightCheck,
        handlePreflightFix,
        handlePin,
        openArtifactPath,
        openRecommendationTarget,
        copyTextValue,
        copyArtifactPayload,
        togglePinArtifactKey,
        approvingIds,
        approveErrors,
        n8nOpenBusyKey,
        handleApprove,
        handleResume,
        handleGuidedRecovery,
        runRecoveryAction,
        handleOneClickRecovery,
        handleApprovalDecision,
        cancelPendingDispatch,
        handleSend,
        handleSuggestionClick,
        handleQuickProgramAction,
        handleTelegramListenerCommand,
        handleKeyDown,
        handleInputPaste,
        handleBackgroundClick,
        handleComposerModeSelect,
        handleCycleComposerMode,
        handleApplyWebSearchTemplate,
        handleApplySummaryTemplate,
    };
}

export type LauncherActions = ReturnType<typeof useLauncherActions>;
