use anyhow::Result;

use crate::controller::actions::ActionRunner;

impl ActionRunner {
    pub(in crate::controller::actions) fn mail_send_latest_message(
        goal: Option<&str>,
        draft_id: Option<&str>,
    ) -> Result<String> {
        let fallback = Self::preferred_mail_recipient(goal).unwrap_or_default();
        let subject_hint = Self::preferred_mail_subject(goal).unwrap_or_default();
        let marker_hint = Self::preferred_run_scope_marker(goal).unwrap_or_default();
        let draft_hint = draft_id.unwrap_or_default().to_string();
        let strict_draft_check =
            Self::bool_env_with_default("STEER_MAIL_STRICT_DRAFT_CHECK", false);
        let strict_draft_check_arg = if strict_draft_check { "1" } else { "0" }.to_string();
        let lines = [
            "on sent_message_exists(targetSubject, targetRecipient, targetMarker)",
            "set matched to false",
            "tell application \"Mail\"",
            "repeat with ac in accounts",
            "try",
            "set sentBoxes to {}",
            "repeat with sentName in {\"Sent Messages\", \"Sent Mail\", \"Sent\", \"보낸 편지함\", \"All Mail\"}",
            "try",
            "set end of sentBoxes to (mailbox (sentName as text) of ac)",
            "end try",
            "end repeat",
            "if (count of sentBoxes) = 0 then",
            "try",
            "set sentMbx to sent mailbox of ac",
            "if sentMbx is not missing value then set end of sentBoxes to sentMbx",
            "end try",
            "end if",
            "repeat with sentMbx in sentBoxes",
            "if matched then exit repeat",
            "set sentCount to count of messages of sentMbx",
            "if sentCount > 0 then",
            "set lowerBound to sentCount - 120",
            "if lowerBound < 1 then set lowerBound to 1",
            "repeat with idx from sentCount to lowerBound by -1",
            "set sm to message idx of sentMbx",
            "set ss to \"\"",
            "set bodyText to \"\"",
            "set recipientText to \"\"",
            "try",
            "set ss to subject of sm as text",
            "end try",
            "try",
            "set bodyText to content of sm as text",
            "end try",
            "try",
            "repeat with r in to recipients of sm",
            "set recipientText to recipientText & \" \" & (address of r as text)",
            "end repeat",
            "end try",
            "set subjectOk to false",
            "if targetSubject is \"\" then",
            "set subjectOk to true",
            "else if ss is targetSubject then",
            "set subjectOk to true",
            "end if",
            "set markerOk to false",
            "if targetMarker is \"\" then",
            "set markerOk to true",
            "else if ss contains targetMarker or bodyText contains targetMarker then",
            "set markerOk to true",
            "end if",
            "set recipientOk to false",
            "if targetRecipient is \"\" then",
            "set recipientOk to true",
            "else if recipientText contains targetRecipient then",
            "set recipientOk to true",
            "end if",
            "if subjectOk and markerOk and recipientOk then",
            "set matched to true",
            "exit repeat",
            "end if",
            "end repeat",
            "end if",
            "end repeat",
            "if matched is false then",
            "set inboxBoxes to {}",
            "repeat with inboxName in {\"INBOX\", \"Inbox\", \"받은 편지함\"}",
            "try",
            "set end of inboxBoxes to (mailbox (inboxName as text) of ac)",
            "end try",
            "end repeat",
            "repeat with inboxMbx in inboxBoxes",
            "if matched then exit repeat",
            "set inboxCount to count of messages of inboxMbx",
            "if inboxCount > 0 then",
            "set inboxLowerBound to inboxCount - 120",
            "if inboxLowerBound < 1 then set inboxLowerBound to 1",
            "repeat with idx from inboxCount to inboxLowerBound by -1",
            "set im to message idx of inboxMbx",
            "set isub to \"\"",
            "set ibody to \"\"",
            "set irecip to \"\"",
            "try",
            "set isub to subject of im as text",
            "end try",
            "try",
            "set ibody to content of im as text",
            "end try",
            "try",
            "repeat with r in to recipients of im",
            "set irecip to irecip & \" \" & (address of r as text)",
            "end repeat",
            "end try",
            "set subjectOk to false",
            "if targetSubject is \"\" then",
            "set subjectOk to true",
            "else if isub is targetSubject then",
            "set subjectOk to true",
            "end if",
            "set markerOk to false",
            "if targetMarker is \"\" then",
            "set markerOk to true",
            "else if isub contains targetMarker or ibody contains targetMarker then",
            "set markerOk to true",
            "end if",
            "set recipientOk to false",
            "if targetRecipient is \"\" then",
            "set recipientOk to true",
            "else if irecip contains targetRecipient then",
            "set recipientOk to true",
            "end if",
            "if subjectOk and markerOk and recipientOk then",
            "set matched to true",
            "exit repeat",
            "end if",
            "end repeat",
            "end if",
            "end repeat",
            "end if",
            "end try",
            "if matched then exit repeat",
            "end repeat",
            "end tell",
            "return matched",
            "end sent_message_exists",
            "on run argv",
            "set fallbackAddress to \"\"",
            "set subjectHint to \"\"",
            "set markerHint to \"\"",
            "set draftHint to \"\"",
            "set strictDraftCheck to true",
            "if (count of argv) >= 1 then set fallbackAddress to item 1 of argv",
            "if (count of argv) >= 2 then set subjectHint to item 2 of argv",
            "if (count of argv) >= 3 then set markerHint to item 3 of argv",
            "if (count of argv) >= 4 then set draftHint to item 4 of argv",
            "if (count of argv) >= 5 then",
            "set strictArg to item 5 of argv",
            "if strictArg is \"0\" then set strictDraftCheck to false",
            "end if",
            "tell application \"Mail\" to activate",
            "tell application \"Mail\"",
            "set beforeOutgoing to (count of outgoing messages)",
            "if beforeOutgoing = 0 then",
            "return \"no_draft|0|0||\"",
            "end if",
            "if draftHint is \"\" then",
            "return \"no_draft|\" & beforeOutgoing & \"|\" & beforeOutgoing & \"|||\" & \"|0\"",
            "end if",
            "set _msg to missing value",
            "if draftHint is not \"\" then",
            "repeat with candidate in outgoing messages",
            "try",
            "if (id of candidate as text) is draftHint then",
            "set _msg to candidate",
            "exit repeat",
            "end if",
            "end try",
            "end repeat",
            "end if",
            "if _msg is missing value then",
            "return \"draft_not_found|\" & beforeOutgoing & \"|\" & beforeOutgoing & \"|||\" & draftHint & \"|0\"",
            "end if",
            "set visible of _msg to false",
            "set _subject to \"\"",
            "set _recipient to \"\"",
            "try",
            "set _subject to (subject of _msg as text)",
            "end try",
            "if subjectHint is not \"\" and _subject is \"\" then",
            "set subject of _msg to subjectHint",
            "set _subject to subjectHint",
            "end if",
            "if fallbackAddress is not \"\" then",
            "set hasTarget to false",
            "repeat with r in to recipients of _msg",
            "try",
            "if (address of r as text) is fallbackAddress then set hasTarget to true",
            "end try",
            "end repeat",
            "if hasTarget is false then",
            "make new to recipient at end of to recipients of _msg with properties {address:fallbackAddress}",
            "end if",
            "set _recipient to \"\"",
            "repeat with r in to recipients of _msg",
            "try",
            "set _recipient to _recipient & \" \" & (address of r as text)",
            "end try",
            "end repeat",
            "else",
            "if (count of to recipients of _msg) = 0 then",
            "return \"missing_recipient|\" & beforeOutgoing & \"|\" & beforeOutgoing & \"||\" & _subject",
            "else",
            "try",
            "set _recipient to \"\"",
            "repeat with r in to recipients of _msg",
            "try",
            "set _recipient to _recipient & \" \" & (address of r as text)",
            "end try",
            "end repeat",
            "end try",
            "end if",
            "end if",
            "set _draftId to \"\"",
            "set _bodyText to \"\"",
            "set _bodyLen to 0",
            "try",
            "set _draftId to (id of _msg as text)",
            "end try",
            "try",
            "set _bodyText to (content of _msg as text)",
            "end try",
            "if _bodyText is missing value then set _bodyText to \"\"",
            "try",
            "set _bodyLen to (length of _bodyText)",
            "end try",
            "if _bodyLen <= 2 then",
            "return \"empty_body|\" & beforeOutgoing & \"|\" & beforeOutgoing & \"|\" & _recipient & \"|\" & _subject & \"|\" & _draftId & \"|\" & _bodyLen",
            "end if",
            "if strictDraftCheck and markerHint is not \"\" and (_bodyText does not contain markerHint) then",
            "set fallbackMsg to missing value",
            "repeat with idx from beforeOutgoing to 1 by -1",
            "set candidate to item idx of outgoing messages",
            "set candidateSubject to \"\"",
            "set candidateContent to \"\"",
            "set candidateRecipients to \"\"",
            "try",
            "set candidateSubject to (subject of candidate as text)",
            "end try",
            "try",
            "set candidateContent to (content of candidate as text)",
            "end try",
            "if candidateContent is missing value then set candidateContent to \"\"",
            "try",
            "repeat with r in to recipients of candidate",
            "try",
            "set candidateRecipients to candidateRecipients & \" \" & (address of r as text)",
            "end try",
            "end repeat",
            "end try",
            "set subjectOk to (subjectHint is \"\" or candidateSubject is subjectHint)",
            "set recipientOk to (fallbackAddress is \"\" or candidateRecipients contains fallbackAddress)",
            "if subjectOk and recipientOk and candidateContent contains markerHint then",
            "set fallbackMsg to candidate",
            "exit repeat",
            "end if",
            "end repeat",
            "if fallbackMsg is missing value then",
            "if strictDraftCheck then",
            "return \"missing_marker|\" & beforeOutgoing & \"|\" & beforeOutgoing & \"|\" & _recipient & \"|\" & _subject & \"|\" & _draftId & \"|\" & _bodyLen",
            "end if",
            "else",
            "set _msg to fallbackMsg",
            "set _subject to \"\"",
            "set _recipient to \"\"",
            "set _draftId to \"\"",
            "set _bodyText to \"\"",
            "set _bodyLen to 0",
            "try",
            "set _subject to (subject of _msg as text)",
            "end try",
            "try",
            "if (count of to recipients of _msg) > 0 then",
            "set _recipient to \"\"",
            "repeat with r in to recipients of _msg",
            "try",
            "set _recipient to _recipient & \" \" & (address of r as text)",
            "end try",
            "end repeat",
            "end if",
            "end try",
            "try",
            "set _draftId to (id of _msg as text)",
            "end try",
            "try",
            "set _bodyText to (content of _msg as text)",
            "end try",
            "if _bodyText is missing value then set _bodyText to \"\"",
            "try",
            "set _bodyLen to (length of _bodyText)",
            "end try",
            "end if",
            "end if",
            "if strictDraftCheck and markerHint is \"\" and subjectHint is not \"\" and _bodyLen <= 2 then",
            "if strictDraftCheck then",
            "return \"empty_body|\" & beforeOutgoing & \"|\" & beforeOutgoing & \"|\" & _recipient & \"|\" & _subject & \"|\" & _draftId & \"|\" & _bodyLen",
            "end if",
            "set fallbackMsg to missing value",
            "repeat with idx from beforeOutgoing to 1 by -1",
            "set candidate to item idx of outgoing messages",
            "set candidateSubject to \"\"",
            "set candidateContent to \"\"",
            "set candidateRecipients to \"\"",
            "set candidateLen to 0",
            "try",
            "set candidateSubject to (subject of candidate as text)",
            "end try",
            "try",
            "set candidateContent to (content of candidate as text)",
            "end try",
            "if candidateContent is missing value then set candidateContent to \"\"",
            "try",
            "set candidateLen to (length of candidateContent)",
            "end try",
            "try",
            "repeat with r in to recipients of candidate",
            "try",
            "set candidateRecipients to candidateRecipients & \" \" & (address of r as text)",
            "end try",
            "end repeat",
            "end try",
            "set subjectOk to (subjectHint is \"\" or candidateSubject is subjectHint)",
            "set recipientOk to (fallbackAddress is \"\" or candidateRecipients contains fallbackAddress)",
            "if subjectOk and recipientOk and candidateLen > 2 then",
            "set fallbackMsg to candidate",
            "exit repeat",
            "end if",
            "end repeat",
            "if fallbackMsg is missing value then",
            "return \"empty_body|\" & beforeOutgoing & \"|\" & beforeOutgoing & \"|\" & _recipient & \"|\" & _subject & \"|\" & _draftId & \"|\" & _bodyLen",
            "end if",
            "set _msg to fallbackMsg",
            "set _subject to \"\"",
            "set _recipient to \"\"",
            "set _draftId to \"\"",
            "set _bodyText to \"\"",
            "set _bodyLen to 0",
            "try",
            "set _subject to (subject of _msg as text)",
            "end try",
            "try",
            "if (count of to recipients of _msg) > 0 then set _recipient to (address of first to recipient of _msg as text)",
            "end try",
            "try",
            "set _draftId to (id of _msg as text)",
            "end try",
            "try",
            "set _bodyText to (content of _msg as text)",
            "end try",
            "if _bodyText is missing value then set _bodyText to \"\"",
            "try",
            "set _bodyLen to (length of _bodyText)",
            "end try",
            "end if",
            "try",
            "send _msg",
            "end try",
            "try",
            "tell application \"System Events\" to keystroke \"d\" using {command down, shift down}",
            "end try",
            "set afterOutgoing to beforeOutgoing",
            "repeat with _tick from 1 to 20",
            "delay 0.4",
            "set afterOutgoing to (count of outgoing messages)",
            "set checkSubject to _subject",
            "if checkSubject is \"\" then set checkSubject to subjectHint",
            "set checkRecipient to _recipient",
            "if checkRecipient is \"\" then set checkRecipient to fallbackAddress",
            "if afterOutgoing = 0 then return \"sent_confirmed|\" & beforeOutgoing & \"|\" & afterOutgoing & \"|\" & checkRecipient & \"|\" & checkSubject & \"|\" & _draftId & \"|\" & _bodyLen",
            "if afterOutgoing < beforeOutgoing then return \"sent_confirmed|\" & beforeOutgoing & \"|\" & afterOutgoing & \"|\" & checkRecipient & \"|\" & checkSubject & \"|\" & _draftId & \"|\" & _bodyLen",
            "if _draftId is not \"\" then",
            "set draftStillExists to false",
            "repeat with candidate in outgoing messages",
            "try",
            "if (id of candidate as text) is _draftId then",
            "set draftStillExists to true",
            "exit repeat",
            "end if",
            "end try",
            "end repeat",
            "if draftStillExists is false then return \"sent_confirmed|\" & beforeOutgoing & \"|\" & afterOutgoing & \"|\" & checkRecipient & \"|\" & checkSubject & \"|\" & _draftId & \"|\" & _bodyLen",
            "end if",
            "end repeat",
            "end tell",
            "return \"sent_pending|\" & beforeOutgoing & \"|\" & afterOutgoing & \"|\" & _recipient & \"|\" & _subject & \"|\" & _draftId & \"|\" & _bodyLen",
            "end run",
        ];
        let out = crate::applescript::run_with_args(
            &lines,
            &[
                fallback,
                subject_hint,
                marker_hint,
                draft_hint,
                strict_draft_check_arg,
            ],
        )?;
        Ok(out.trim().to_string())
    }
}
